//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはテンプレートから生成されました。
//
//     このファイルを手動で変更すると、アプリケーションで予期しない動作が発生する可能性があります。
//     このファイルに対する手動の変更は、コードが再生成されると上書きされます。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BasicSpa.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public int Id { get; set; }
        public string Title { get; set; }
        public string ProductUrl { get; set; }
        public string DownloadUrl { get; set; }
        public string Description { get; set; }
        public string Publisher { get; set; }
        public string PublisherUrl { get; set; }
        public string ImageUrl { get; set; }
        public Nullable<decimal> Price { get; set; }
    }
}
